version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  room-service:
    build: .
    container_name: room-service
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - redis
